vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        user_image:
            uri_prefix: /img/users
            upload_destination: '%kernel.project_dir%/public/img/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_cosplay:
            uri_prefix: /img/cosplays
            upload_destination: '%kernel.project_dir%/public/img/cosplays'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_coussins:
            uri_prefix: /img/coussins
            upload_destination: '%kernel.project_dir%/public/img/coussins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_figurines:
            uri_prefix: /img/figurines
            upload_destination: '%kernel.project_dir%/public/img/figurines'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_portes_cles:
            uri_prefix: /img/portes-cles
            upload_destination: '%kernel.project_dir%/public/img/portes-cles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_pulls:
            uri_prefix: /img/pulls
            upload_destination: '%kernel.project_dir%/public/img/pulls'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer